name: Deploy to EC2 on Push to Master

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/cicd-keypair.pem
          chmod 600 ~/.ssh/cicd-keypair.pem
          ssh-keyscan -H ec2-13-114-103-130.ap-northeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
      - name: Configure Git safe.directory
        run: |
          git config --global --add safe.directory /home/ubuntu/Hello-CICD

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/cicd-keypair.pem ubuntu@ec2-13-114-103-130.ap-northeast-1.compute.amazonaws.com 'git config --global --add safe.directory /home/ubuntu/Hello-CICD && cd /home/ubuntu/Hello-CICD && git pull origin master && docker-compose down && docker-compose up --build'
