name: Deploy to EC2 on Push to Master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 3.112.230.42 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@3.112.230.42 << EOF
            cd /home/ubuntu/Hello-CICD
            git pull origin master
            docker compose down
            docker compose up --build
            # Commands to stop and remove the current Docker container
            # Commands to build/run the new Docker container
            # For example: docker-compose up -d --build
          EOF
