name: Lint and Tag

on: [push]

jobs:
  lint-and-tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Set up your project environment, for example, Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Install pylint
    - name: Install pylint
      run: pip install pylint

    # Run pylint and handle the output
    - name: Run Linter
      id: lint
      run: |
        pylint_output=$(pylint your_code_directory_or_file --output-format=text)
        echo "$pylint_output"
        lint_score=$(echo "$pylint_output" | grep "Your code has been rated at" | sed 's/.*rated at \([-0-9.]*\)\/.*/\1/')
        echo "LINT_SCORE=$lint_score" >> $GITHUB_ENV
        if [[ "$lint_score" != "" && $(echo "$lint_score < 7" | bc) -eq 1 ]]; then
          exit 1
        fi

    # Conditional step to check the lint score and create a tag
    - name: Create Tag
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create Snapshot Tag
      if: ${{ github.ref != 'refs/heads/master' }}
      run: |
        BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
        SNAPSHOT_TAG=v$(date +'%Y%m%d%H%M%S')-SNAPSHOT
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag $SNAPSHOT_TAG
        git push origin $SNAPSHOT_TAG
