name: Lint and Tag

on: [push]

jobs:
  lint-and-tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install flake8
      run: pip install flake8

    # Run the linter and calculate the score
    - name: Run Linter
      id: lint
      run: |
        # Run flake8 and save the output
        flake8 --output-file lint-report.txt
  

    # Conditional step to check the lint score and create a tag
    - name: Check Lint Score and Tag
      if: ${{ steps.lint.outputs.score > 8 }}
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ]; then
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        else
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')-SNAPSHOT"
          
        fi
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag $TAG_NAME
        git push origin $TAG_NAME
